[package]
name = "embed-evm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
ethers = { version = "2.0.11" }
swift-bridge = "0.1.52"

[build-dependencies]
ethers = { version = "2.0.11", features = ["abigen-online"] }
swift-bridge = "0.1.52"
